openapi: 3.0.0
info:
  description: API documentation of Workout service.
  title: Workout service API
  version: "1.0"
servers:
  - url: https://todo.cz
security:
  - httpBearer: []
tags:
  - description: Just for testing purposes.
    name: Test operations
paths:
  /activity:
    get:
      summary: All activities.
      operationId: GetActivities
      responses:
        "200":
          description: All activities.
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ActivityResponse"
    post:
      summary: Create activity.
      operationId: CreateActivity
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: "#/components/schemas/ActivityUpdate"
        required: true
      responses:
        "200":
          description: An example data
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/ActivityResponse"
  /activity/{id}:
    get:
      summary: Get an activity.
      operationId: GetActivity
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
          description: An activity ID.
      responses:
        "200":
          description: An activity data
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/ActivityResponse"
    put:
      summary: Update the activity.
      operationId: UpdateActivity
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: number
          description: An activity ID.
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: "#/components/schemas/ActivityUpdate"
        required: true
      responses:
        "200":
          description: An updated activity data
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/ActivityResponse"
components:
  schemas:
    ActivityResponse:
      description: A activity response.
      title: ActivityResponse
      type: object
      properties:
        id:
          type: number
          description: "Activity ID."
        name:
          type: string
          description: "Activity name."
      required:
        - id
        - name
      example:
        id: "123456"
        name: "Afternoon Ride"
    ActivityUpdate:
        type: object
        properties:
          name:
            type: string
            description: "Activity name."
        required:
          - id
          - name
